/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104414-geda2a50c8e-20211022"
#endif /* AVUTIL_FFVERSION_H */
